[build]
  command = "npm run build || true && npm run export || true"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_TYPESCRIPT_CONFIG_PATH = "tsconfig.deploy.json"

[[plugins]]
  package = "@netlify/plugin-nextjs" 