name: Edison Maintenance Agent

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to run'
        required: false
        default: 'report'
        type: choice
        options:
          - full
          - organize
          - fix
          - ui
          - cleanup
          - update
          - deploy-fix
          - restructure
          - report
      dry_run:
        description: 'Dry run (no changes)'
        required: false
        default: false
        type: boolean
      safety:
        description: 'Safety level for updates'
        required: false
        default: 'safe'
        type: choice
        options:
          - safe
          - moderate
          - aggressive
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
    branches:
      - main

jobs:
  auto-update:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save node-fetch
      
      - name: Run auto-updater
        run: node config/.github/scripts/auto-updater.js safe
      
      - name: Push updates if any
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git push origin main
          else
            echo "No changes to push"
          fi
      
      - name: Upload update report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: update-report
          path: .github/reports/auto-update-report.md

  code-organization:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run code organization script
        run: node config/.github/scripts/organize-code.js
      
      - name: Create PR for code organization
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "refactor: organize code structure"
          title: "🧹 Code Organization"
          body: "The Edison Agent has detected opportunities to improve the code organization and structure."
          branch: "agent-code-organization"
          labels: "code-structure,automated"

  code-quality:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint with auto-fix
        run: npx eslint --fix --max-warnings=0 "src/**/*.{js,jsx,ts,tsx}"
      
      - name: Run TypeScript compiler for type checking
        run: npx tsc --noEmit
      
      - name: Run dead code elimination
        run: node config/.github/scripts/dead-code-eliminator.js
      
      - name: Run import optimizer
        run: npx organize-imports-cli src/**/*.ts src/**/*.tsx
      
      - name: Create PR for code quality fixes
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "fix: automatic code quality improvements"
          title: "🔧 Code Quality Improvements"
          body: "The Edison Agent has automatically fixed code quality issues."
          branch: "agent-code-quality"
          labels: "code-quality,automated"

  ui-improvements:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run CSS optimizer
        run: npx postcss src/**/*.css --use autoprefixer cssnano --replace
      
      - name: Run UI consistency checker
        run: node config/.github/scripts/ui-consistency-check.js
      
      - name: Run accessibility fixer
        run: node config/.github/scripts/accessibility-fixer.js
      
      - name: Run responsive design checker
        run: node config/.github/scripts/responsive-design-check.js
      
      - name: Create PR for UI improvements
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "style: automatic UI improvements"
          title: "✨ UI Enhancements"
          body: "The Edison Agent has automatically improved UI consistency, accessibility, and responsive design."
          branch: "agent-ui-improvements"
          labels: "ui,automated"

  file-cleanup:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run duplicate file detector
        run: node config/.github/scripts/duplicate-detector.js
      
      - name: Run unused file detector
        run: node config/.github/scripts/unused-file-detector.js
      
      - name: Generate file cleanup report
        run: node config/.github/scripts/generate-cleanup-report.js
      
      - name: Run automated cleanup
        run: node config/.github/scripts/auto-cleanup.js
      
      - name: Create PR for file cleanup
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: file system cleanup"
          title: "🗑️ File Cleanup"
          body: "The Edison Agent has removed duplicate and unused files, and reorganized the file structure."
          branch: "agent-file-cleanup"
          labels: "cleanup,automated"

  bug-detection:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests to find bugs
        run: npm test || true
      
      - name: Run static analysis
        run: npx jscpd src --min-lines 5 --max-size 1mb
      
      - name: Run bug detector
        run: node config/.github/scripts/bug-detector.js
      
      - name: Run automated fixes
        run: node config/.github/scripts/auto-fix-bugs.js
      
      - name: Create PR for bug fixes
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "fix: automatic bug fixes"
          title: "🐛 Bug Fixes"
          body: "The Edison Agent has automatically detected and fixed bugs."
          branch: "agent-bug-fixes"
          labels: "bug,automated"

  deploy-fix:
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save @vercel/client node-fetch axios
      
      - name: Run deployment fixer
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: node config/.github/scripts/edison-agent.js deploy-fix ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}
      
      - name: Check for changes
        id: git-check
        run: echo "::set-output name=changes::$(if git status --porcelain | grep .; then echo true; else echo false; fi)"
      
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Fix: Automated Vercel deployment fixes'
          commit-message: 'Fix: Automated Vercel deployment fixes'
          branch: auto-deployment-fixes
          delete-branch: true
          body: |
            This PR contains automated fixes for Vercel deployment issues.
            
            Changes:
            - Fixed deployment configuration issues
            - Updated incompatible dependencies
            - Resolved memory limitation problems
            - Adjusted build settings for better compatibility
      
      - name: Upload deployment fix report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: deployment-fix-report
          path: .github/reports/deployment-fix-*.md
          retention-days: 7

  mini-organizer:
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'deep-restructure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run mini organizer for code restructuring
        run: node config/.github/scripts/edison-agent.js restructure ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}
      
      - name: Check for changes
        id: git-check
        run: echo "::set-output name=changes::$(if git status --porcelain | grep .; then echo true; else echo false; fi)"
      
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Refactor: Deep code reorganization'
          commit-message: 'Refactor: Deep code reorganization by Mini Organizer'
          branch: deep-code-restructuring
          delete-branch: true
          body: |
            This PR contains a deep restructuring of the codebase for optimal organization.
            
            Changes:
            - Moved files to optimal locations based on their function
            - Created proper directory structure for components, utilities, hooks, etc.
            - Created index files for clean imports
            - Updated import paths throughout the codebase
            - Removed unused files
            
            Please review the changes carefully as this is a significant code reorganization.
      
      - name: Upload mini organizer report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mini-organizer-report
          path: .github/reports/mini-organizer-*.md
          retention-days: 7 