name: Edison Maintenance Agent

on:
  schedule:
    - cron: '0 2 * * 1'  # Run weekly on Mondays at 2 AM instead of daily
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to run'
        required: false
        default: 'report'
        type: choice
        options:
          - full
          - organize
          - fix
          - ui
          - cleanup
          - update
          - deploy-fix
          - restructure
          - report
      dry_run:
        description: 'Dry run (no changes)'
        required: false
        default: true
        type: boolean
      safety:
        description: 'Safety level for updates'
        required: false
        default: 'safe'
        type: choice
        options:
          - safe
          - moderate
          - aggressive
      skip_if_recent:
        description: 'Skip if run recently (within 7 days)'
        required: false
        default: true
        type: boolean
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
    branches:
      - main

jobs:
  pre-check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        if: github.event_name == 'schedule' && github.event.inputs.skip_if_recent == 'true'
        run: |
          LAST_RUN=$(curl -s https://api.github.com/repos/${{ github.repository }}/actions/workflows/edison-agent.yml/runs?status=completed&per_page=1 | jq -r '.workflow_runs[0].created_at')
          if [[ -z "$LAST_RUN" ]]; then
            echo "::set-output name=should_run::true"
          else
            LAST_RUN_SECONDS=$(date -d "$LAST_RUN" +%s)
            NOW_SECONDS=$(date +%s)
            DIFF_DAYS=$(( ($NOW_SECONDS - $LAST_RUN_SECONDS) / 86400 ))
            if [[ $DIFF_DAYS -ge 7 ]]; then
              echo "::set-output name=should_run::true"
            else
              echo "::set-output name=should_run::false"
              echo "Skipping run, last execution was $DIFF_DAYS days ago"
            fi
          fi
        shell: bash

  auto-update:
    needs: pre-check
    if: (github.event_name != 'schedule' || needs.pre-check.outputs.should_run == 'true') && (github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save node-fetch
      
      - name: Run auto-updater
        run: node config/.github/scripts/auto-updater.js safe
      
      - name: Push updates if any
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git push origin main
          else
            echo "No changes to push"
          fi
      
      - name: Upload update report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: update-report
          path: .github/reports/auto-update-report.md

  code-organization:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run code organization script
        run: node config/.github/scripts/organize-code.js
      
      - name: Create PR for code organization
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "refactor: organize code structure"
          title: "🧹 Code Organization Suggestions"
          body: "The Edison Agent has identified some potential improvements to the code organization and structure."
          branch: "agent-code-organization"
          labels: "code-structure,automated"

  code-quality:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint with auto-fix
        run: npx eslint --fix --max-warnings=0 "src/**/*.{js,jsx,ts,tsx}"
      
      - name: Run TypeScript compiler for type checking
        run: npx tsc --noEmit
      
      - name: Run dead code elimination
        run: node config/.github/scripts/dead-code-eliminator.js
      
      - name: Run import optimizer
        run: npx organize-imports-cli src/**/*.ts src/**/*.tsx
      
      - name: Create PR for code quality fixes
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "fix: code quality improvements"
          title: "🔧 Code Quality Suggestions"
          body: "The Edison Agent has identified some potential code quality improvements for your consideration."
          branch: "agent-code-quality"
          labels: "code-quality,automated"

  ui-improvements:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run CSS optimizer
        run: npx postcss src/**/*.css --use autoprefixer cssnano --replace
      
      - name: Run UI consistency checker
        run: node config/.github/scripts/ui-consistency-check.js
      
      - name: Run accessibility fixer
        run: node config/.github/scripts/accessibility-fixer.js
      
      - name: Run responsive design checker
        run: node config/.github/scripts/responsive-design-check.js
      
      - name: Create PR for UI improvements
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "style: UI improvements"
          title: "✨ UI Enhancement Suggestions"
          body: "The Edison Agent has identified potential improvements for UI consistency, accessibility, and responsive design."
          branch: "agent-ui-improvements"
          labels: "ui,automated"

  file-cleanup:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run duplicate file detector
        run: node config/.github/scripts/duplicate-detector.js
      
      - name: Run unused file detector
        run: node config/.github/scripts/unused-file-detector.js
      
      - name: Generate file cleanup report
        run: node config/.github/scripts/generate-cleanup-report.js
      
      - name: Run automated cleanup
        run: node config/.github/scripts/auto-cleanup.js
      
      - name: Create PR for file cleanup
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: file system cleanup"
          title: "🗑️ File Cleanup Suggestions"
          body: "The Edison Agent has identified potential duplicate and unused files that might be candidates for cleanup."
          branch: "agent-file-cleanup"
          labels: "cleanup,automated"

  bug-detection:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests to find bugs
        run: npm test || true
      
      - name: Run static analysis
        run: npx jscpd src --min-lines 5 --max-size 1mb
      
      - name: Run bug detector
        run: node config/.github/scripts/bug-detector.js
      
      - name: Run automated fixes
        run: node config/.github/scripts/auto-fix-bugs.js
      
      - name: Create PR for bug fixes
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "fix: suggested bug fixes"
          title: "🐛 Potential Bug Fix Suggestions"
          body: "The Edison Agent has identified some potential issues that might need addressing."
          branch: "agent-bug-fixes"
          labels: "bug,automated"

  deploy-fix:
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save @vercel/client node-fetch axios
      
      - name: Run deployment fixer
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: node config/.github/scripts/edison-agent.js deploy-fix ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}
      
      - name: Check for changes
        id: git-check
        run: echo "::set-output name=changes::$(if git status --porcelain | grep .; then echo true; else echo false; fi)"
      
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Fix: Suggested Vercel deployment improvements'
          commit-message: 'Fix: Suggested Vercel deployment improvements'
          branch: auto-deployment-fixes
          delete-branch: true
          body: |
            This PR contains suggested fixes for potential Vercel deployment issues.
            
            Suggestions:
            - Possible deployment configuration adjustments
            - Dependency compatibility recommendations
            - Memory optimization suggestions
            - Build setting considerations for better compatibility
      
      - name: Upload deployment fix report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: deployment-fix-report
          path: .github/reports/deployment-fix-*.md
          retention-days: 7

  mini-organizer:
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'deep-restructure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run mini organizer for code restructuring
        run: node config/.github/scripts/edison-agent.js restructure ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}
      
      - name: Check for changes
        id: git-check
        run: echo "::set-output name=changes::$(if git status --porcelain | grep .; then echo true; else echo false; fi)"
      
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Refactor: Proposed code organization suggestions'
          commit-message: 'Refactor: Proposed code organization by Mini Organizer'
          branch: deep-code-restructuring
          delete-branch: true
          body: |
            This PR contains suggestions for potential code organization improvements.
            
            Suggestions:
            - File location optimizations based on function
            - Directory structure recommendations for components, utilities, hooks, etc.
            - Index file creation for cleaner imports
            - Import path updates
            - Identification of potentially unused files
            
            Please review these suggestions at your convenience and feel free to reject, modify, or accept them as you see fit.
      
      - name: Upload mini organizer report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mini-organizer-report
          path: .github/reports/mini-organizer-*.md
          retention-days: 7 