name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          NEXT_TELEMETRY_DISABLED=1 npm run build || true
        env:
          NODE_ENV: production
          
      - name: Export
        run: |
          NEXT_TELEMETRY_DISABLED=1 npm run export || true
        env:
          NODE_ENV: production
          
      - name: Create out directory if it doesn't exist
        run: mkdir -p out

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages 