name: Edison Maintenance Agent

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    types: [labeled]
    branches: [main]

jobs:
  auto-update:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install --no-save node-fetch
      
      - name: Run auto-updater
        run: node .github/scripts/auto-updater.js safe
      
      - name: Push updates if any
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git push origin main
          else
            echo "No changes to push"
          fi
      
      - name: Upload update report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: update-report
          path: .github/reports/auto-update-report.md

  code-organization:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run code organization script
        run: node .github/scripts/organize-code.js
      
      - name: Create PR for code organization
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "refactor: organize code structure"
          title: "🧹 Code Organization"
          body: "The Edison Agent has detected opportunities to improve the code organization and structure."
          branch: "agent-code-organization"
          labels: "code-structure,automated"

  code-quality:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint with auto-fix
        run: npx eslint --fix --max-warnings=0 "src/**/*.{js,jsx,ts,tsx}"
      
      - name: Run TypeScript compiler for type checking
        run: npx tsc --noEmit
      
      - name: Run dead code elimination
        run: node .github/scripts/dead-code-eliminator.js
      
      - name: Run import optimizer
        run: npx organize-imports-cli src/**/*.ts src/**/*.tsx
      
      - name: Create PR for code quality fixes
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "fix: automatic code quality improvements"
          title: "🔧 Code Quality Improvements"
          body: "The Edison Agent has automatically fixed code quality issues."
          branch: "agent-code-quality"
          labels: "code-quality,automated"

  ui-improvements:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run CSS optimizer
        run: npx postcss src/**/*.css --use autoprefixer cssnano --replace
      
      - name: Run UI consistency checker
        run: node .github/scripts/ui-consistency-check.js
      
      - name: Run accessibility fixer
        run: node .github/scripts/accessibility-fixer.js
      
      - name: Run responsive design checker
        run: node .github/scripts/responsive-design-check.js
      
      - name: Create PR for UI improvements
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "style: automatic UI improvements"
          title: "✨ UI Enhancements"
          body: "The Edison Agent has automatically improved UI consistency, accessibility, and responsive design."
          branch: "agent-ui-improvements"
          labels: "ui,automated"

  file-cleanup:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run duplicate file detector
        run: node .github/scripts/duplicate-detector.js
      
      - name: Run unused file detector
        run: node .github/scripts/unused-file-detector.js
      
      - name: Generate file cleanup report
        run: node .github/scripts/generate-cleanup-report.js
      
      - name: Run automated cleanup
        run: node .github/scripts/auto-cleanup.js
      
      - name: Create PR for file cleanup
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: file system cleanup"
          title: "🗑️ File Cleanup"
          body: "The Edison Agent has removed duplicate and unused files, and reorganized the file structure."
          branch: "agent-file-cleanup"
          labels: "cleanup,automated"

  bug-detection:
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'agent-review')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests to find bugs
        run: npm test || true
      
      - name: Run static analysis
        run: npx jscpd src --min-lines 5 --max-size 1mb
      
      - name: Run bug detector
        run: node .github/scripts/bug-detector.js
      
      - name: Run automated fixes
        run: node .github/scripts/auto-fix-bugs.js
      
      - name: Create PR for bug fixes
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "fix: automatic bug fixes"
          title: "🐛 Bug Fixes"
          body: "The Edison Agent has automatically detected and fixed bugs."
          branch: "agent-bug-fixes"
          labels: "bug,automated" 